# Generated by Django 4.1.4 on 2023-01-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='trainer',
            new_name='trainer_name',
        ),
    ]
